config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :quiz, only: [:index, :new, :show]
  resources :result, only: [:show]

  get '/quiz', to: 'quiz#new'
  post '/quiz', to: 'quiz#create'
  post '/result', to: 'result#create'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_and_belongs_to_many :quizzes
	has_one :result
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :quiz
	has_many :answers
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_and_belongs_to_many :answers
	belongs_to :user
	has_one :result
end

app/models/result.rb
class Result < ActiveRecord::Base
	has_many :quizzes
	belongs_to :answer
	#has_and_belongs_to_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :quiz
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController

def index
end

def new
	@questions = Question.all
	#@quiz = Quiz.find(params[:user_id])
end

def create
	puts params
	@quiz = Quiz.new
	@quiz.answers << Answer.find(params["1"].to_i)
	@quiz.answers << Answer.find(params["2"].to_i)
	
	@quiz.save
	redirect_to result_path(@quiz.id)
end

def show
	@quiz = Quiz.find(params[:id])
end

end

app/controllers/result_controller.rb
class ResultController < ApplicationController

	def show
		#@result = Result.find(1)
		#@result = Answer.group(:question_id).count
		#@result = Result.find(params[:id])
		
		@result = Quiz.answers.group(params[:question_id])
		#@result = Result.all.group(:answer_id).count
		#@result = Answer_Id.group(:question_id).count


		#@result = Quiz.find(params[:id])
		#@result = Quiz.find(params[:answer_id])
		##@result = @quiz.group(:id).count
		#@result = Result.new
		#@result = @quiz.answers.group(q.id).count
		#Result.select("answers.*, COUNT(question.id) vote_count").joins(:result).group("question.id").order("result_count DESC")
	end

	##def create
		#@result = Result.find(params[:id])
	#end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Ahhh...Facebook.</h1>
<br>
<h3>The bain of our existence. The time-suck. The drug. The FMO. And yet, you can't leave...</h3>
<br>
<h3>They say, if you hate Facebook, you hate people. Or maybe it's simply a reflection of who we are?</h3>
<br>

<%= button_to "HAVE YOUR SAY", new_quiz_path, :class => "button", :method => :get  %>
<!--<form action="/" method="post">
  <button>HAVE YOUR SAY</button>
</form>-->
<p> Find out what other people like you hate about Facebook the most.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookQuiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quiz/new.html.erb
<h1>Hate or guilty?</h1>
<br><br><br>
<%= form_tag "/quiz", method: "POST" do %>
<% @questions.each do |q| %> 
	<h3><%= q.question %></h3>
	<% q.answers.each do |a| %>
		<h5><%= a.answer %> </h5>
		<%= radio_button_tag(q.id, a.id) %>
	<% end %>
<% end %>
<br />
<br />
<br />
	<%= submit_tag "See Where You Stand" %>
<% end %>

    
   

app/views/quiz/show.html.erb
<h1><%= @quiz.inspect %> </h1>
<p><%= @quiz.answers.inspect %></p>

app/views/result/create.html.erb
<h1>Did You Know?</h1>
<%= @result.inspect %>

app/views/result/index.html.erb
<h1>Did You Know?</h1>

app/views/result/show.html.erb
<h1>Did You Know?</h1>
<%= @result.inspect %>